# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flgVpfgEQMIML7yhlVZt87o4Y_D2z0lD
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Dashboard Reliabilitas Tes", layout="wide")
st.title("📊 Dashboard Analisis Reliabilitas & Konsistensi Tes")

# ==============================
# LOAD DATA
# ==============================
df = pd.read_excel("data_simulasi_50_siswa_20_soal.xlsx")

st.success(f"Data: {df.shape[0]} siswa | {df.shape[1]} soal")

# ==============================
# 1️⃣ RATA-RATA & VARIABILITAS SOAL
# ==============================
st.header("1️⃣ Analisis Statistik Soal")

mean_soal = df.mean()
std_soal = df.std()

col1, col2 = st.columns(2)

with col1:
    st.subheader("📈 Rata-rata Soal")
    fig1, ax1 = plt.subplots(figsize=(8,4))
    ax1.bar(df.columns, mean_soal)
    ax1.set_xticklabels(df.columns, rotation=45)
    st.pyplot(fig1)

with col2:
    st.subheader("📊 Standar Deviasi Soal")
    fig2, ax2 = plt.subplots(figsize=(8,4))
    ax2.bar(df.columns, std_soal)
    ax2.set_xticklabels(df.columns, rotation=45)
    st.pyplot(fig2)

# ==============================
# 2️⃣ KORELASI ANTAR SOAL
# ==============================
st.header("2️⃣ Korelasi Antar Soal")

corr_matrix = df.corr()

fig3, ax3 = plt.subplots(figsize=(10,6))
sns.heatmap(corr_matrix, cmap="coolwarm", ax=ax3)
st.pyplot(fig3)

# ==============================
# 3️⃣ CRONBACH'S ALPHA
# ==============================
st.header("3️⃣ Analisis Reliabilitas (Cronbach's Alpha)")

k = df.shape[1]
var_total = df.sum(axis=1).var()
var_item = df.var().sum()

cronbach_alpha = (k / (k - 1)) * (1 - (var_item / var_total))

st.metric("Nilai Cronbach's Alpha", f"{cronbach_alpha:.3f}")

if cronbach_alpha >= 0.9:
    interpretasi = "Sangat Tinggi"
elif cronbach_alpha >= 0.8:
    interpretasi = "Tinggi"
elif cronbach_alpha >= 0.7:
    interpretasi = "Cukup"
elif cronbach_alpha >= 0.6:
    interpretasi = "Rendah"
else:
    interpretasi = "Tidak Reliabel"

st.write(f"Interpretasi Reliabilitas: **{interpretasi}**")

# ==============================
# 4️⃣ IDENTIFIKASI SOAL TIDAK KONSISTEN
# ==============================
st.header("4️⃣ Identifikasi Soal Tidak Konsisten")

item_total_corr = df.corrwith(df.sum(axis=1))
soal_terendah = item_total_corr.sort_values().head(3)

st.write("3 Soal dengan Korelasi Terendah terhadap Skor Total:")
st.dataframe(soal_terendah)

# ==============================
# 5️⃣ INSIGHT OTOMATIS
# ==============================
st.header("5️⃣ Insight Otomatis")

st.success(f"""
Jumlah Soal: {k}
Cronbach Alpha: {cronbach_alpha:.3f} ({interpretasi})
Soal paling tidak konsisten: {soal_terendah.index[0]}
""")

st.info("Rekomendasi: Evaluasi kembali soal dengan korelasi rendah terhadap skor total.")